### ISSUE TITLE
Paywall not activated on publishing

### ISSUE THREAD

**Issue by ma00** [ma2za/python-substack#12]
I've tested that the paywall is correctly added to the body with this line in .yml file
`    type: "paywall"`
however the paywall is not activated when published.

I believe there are extra options to activate the paywall

**Comment by ma2za** [comment]
Do you mean that you want to put the article behind paywall?

**Comment by ma00** [comment]
right

**Comment by ma2za** [comment]
`audience:
  "everyone" # everyone, only_paid, founding, only_free`

`write_comment_permissions:
  "none" # none, only_paid, everyone`

I added support for audience and write_comment_permissions. The combinations of the two is a mess. I will check the working combinations in the future. You can avoid setting write_comment_permissions and it will inherit from audience.

**Comment by ma00** [comment]
it works! ottimo lavoro
