### ISSUE TITLE
Complete/bypass captcha

### ISSUE THREAD

**Issue by jetnew** [ma2za/python-substack#14]
Hi, I am testing my code and have repeatedly logged into my Substack account via the API, and it has resulted in `SubstackAPIException: APIError(code=401): Please complete the captcha to continue`. How can I complete the captcha (either manually or bypass)?

Thank you so much for your contribution on this package.

**Comment by ma2za** [comment]
Hi, are you using the api locally or on the cloud? Because I used to get this error when I tried to make api calls from the cloud and I was not able to solve it

**Comment by jetnew** [comment]
Indeed, I am running it on the cloud. It works for me locally too. I might inspect the API response to try to manually complete the captcha then. Otherwise, I may shift to Ghost. Thank you for your help.

**Comment by dominicdev** [comment]
hi how are you able to solve this? and how do you do the captcha? I'm running it in google colab

**Comment by suhan1996** [comment]
Works when run locally

**Comment by ma2za** [comment]
Workaround with #25
