### ISSUE TITLE
My profile has no USER_ID?

### ISSUE THREAD

**Issue by danbgoldman** [ma2za/python-substack#16]
My profile page doesn't have a URL of the format shown in the README. It says:

> go to your public profile page, in the URL bar of the browser you find the substack address followed by your USER_ID and your username: [https://substack.com/profile/[USER_ID]-[username]](https://substack.com/profile/%5BUSER_ID%5D-%5Busername%5D)

But my profile isn't under `/profile`, and it's just my username, prefaced by an ampersand:

`https://substack.com/@danbgoldman`

How can I find my user id?

**Comment by ma2za** [comment]
oh, i didn't know this was a thing. Have you found a solution? I know that you can inspect the headers/body of the post request when saving a draft from the website and the user_id should be included. Let me know.

**Comment by danbgoldman** [comment]
I think so: If I view the source for my profile page, there is a JSON
"user_id" value in several places that looks promising. But I haven't tried
it with the API yet.

**Comment by patricker** [comment]
I ran across this issue and updated the instructions in this PR: #23
