### ISSUE TITLE
Get subscribers (count) 

### ISSUE THREAD

**Issue by dacx** [ma2za/python-substack#20]
Hi there,

would you care about adding some analytical information to the package? For example, the current subscribers and the overall subscriber count? It's available at `/api/v1/publication_launch_checklist`. I'd be happy to open a PR if that's cool with you.

Cheers!

**Comment by dacx** [comment]
Created a PR regardless, because I need that feature. https://github.com/ma2za/python-substack/pull/21

**Comment by ma2za** [comment]
nice... thanks
