### ISSUE TITLE
Feature request: supporting the paywall split content type

### ISSUE THREAD

**Issue by suhan1996** [ma2za/python-substack#22]

**Comment by patricker** [comment]
https://github.com/ma2za/python-substack/pull/24
I tested this out, and it looks good.

**Comment by ma2za** [comment]
Nice, thanks

**Comment by suhan1996** [comment]
Great!

One thing for it to work:
"send_paywalled_preview" value is missing, so currently there's no emails sent out to non-paid members if the paywall is added, which is essentially the main reason for this feature (send preview version to non-paid members).
