### ISSUE TITLE
images inside body

### ISSUE THREAD

**Issue by ma00** [ma2za/python-substack#9]
Hi, cool project. 
Any suggestion on how to include images in the body?

**Comment by ma2za** [comment]
hi, thanks.
I just made some updates. If you want to use the script in the examples folder you only need to add a new item to the body in the draft.yaml:

`  type: "captionedImage"
    src: URL to an image`

If you want to use the api you need to first generate a substack url for the image

`new_url = api.get_image(original_url)`

Then you can add the image to the post:

`post.add({"type": "captionedImage", "src": new_url})`

**Comment by ma00** [comment]
it works! thank you!
